name: Continuous Delivery

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install
        run: |
          npm ci
          npm ls

      - name: "Continuous Integration: build"
        run: |
          npm run build --if-present

      - name: "Continuous Integration: lint"
        run: |
          npm run lint --if-present

      - name: "Continuous Integration: test"
        run: |
          npm run test --if-present

      - name: "Retain build artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: .next/
          retention-days: 42

  continuous-deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: "Continuous Deployment: build Docker image"
        env:
          BUILD_DATE: "${{ steps.date.outputs.date }}"
          VCS_REF: "${{ github.event.workflow_run.head_sha }}"
        run: |
          docker-compose build

      - name: Login to Container Registry
        id: containerregistry-login
        run: |
          if [ "${{ secrets.GITHUB_TOKEN }}" != "" ]; then
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $(cut -d'/' -f1 <<< $GITHUB_REPOSITORY) --password-stdin
            echo "##[set-output name=success;]true"
          else
            echo "##[set-output name=success;]false"
          fi
