openapi: 3.1.0
x-stoplight:
  id: xss697rk9a92x
info:
  title: Trouw Service
  version: "1.0"
servers:
  - url: "http://localhost:3000"
paths:
  /huwelijken:
    get:
      summary: Haal alle huwelijken op
      tags: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: "#/components/schemas/huwelijk"
      operationId: get-huwelijken
      description: Haal alle huwelijken op
    post:
      summary: Crieër een nieuw huwelijk
      operationId: post-huwelijken
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/huwelijk"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/huwelijk"
  "/huwelijken/{id}":
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Haal één enkel huwelijk op
      tags: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/huwelijk"
      operationId: get-huwelijken-id
    put:
      summary: Werk een huwelijk bij
      operationId: put-huwelijken-id
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/huwelijk"
    delete:
      summary: Verwijder een huwelijk
      operationId: delete-huwelijken-id
    patch:
      summary: ""
      operationId: patch-huwelijken-id
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/huwelijk"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/huwelijk"
components:
  schemas:
    huwelijk:
      title: Huwelijk
      x-stoplight:
        id: ktufw11iduvhw
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: |
            De unieke identificatie van dit huwelijks
          readOnly: true
        partners:
          x-context: schema.conduction.nl/assent
          description: "De in dit huwelijk betrokken partners, bestaande uit hun instemmming (Assent) en getuigen."
          type: array
          items: {}
        getuigen:
          x-context: schema.conduction.nl/assent
          type: array
          maxItems: 4
          uniqueItems: true
          items: {}
        type:
          description: "Het juridische type van dit huwelijk zo als opgehaald uit de SDG catalogus, zijnde huwelijk, parnterschap of omzetting"
          x-context: schema.conduction.nl/SDGProduct
          type: string
        ceremonie:
          description: "De cermonie (manier) waarop het huwelijk wordt volgrokken. Bijvoorbeeld gratis, flits, eenvoudig of uitgebreid."
          x-context: schema.conduction.nl/SDGProduct
          type: string
        locatie:
          x-context: schema.conduction.nl/SDGProduct
          description: "Verwijzing(uri) naar de **Locatie** in het SDG, bij ophalen kan de query parameter &extend[]=locatie worden gebruikt om een volledig object op te halen."
          type: string
        ambtenaar:
          x-context: schema.conduction.nl/SDGProduct
          description: "Verwijzing(uri) naar de **Ambtenaar** in het SDG, bij ophalen kan de query parameter &extend[]=ambtenaarworden gebruikt om een volledig object op te halen."
          type: string
        status:
          type: string
          enum:
            - concept
            - reported
            - confirmed
            - executed
            - cancelled
          example: concept
          default: concept
        moment:
          type: string
          format: date-time
          description: Het moment waarop het huwelijk aanvangt
        producten:
          type: array
          description: De bij dit huwelijk gekozen extra producten
          x-context: schema.conduction.nl/SDGProduct
          items: {}
        checklist:
          type: object
          properties:
            partners:
              type: object
              description: |-
                Onder partners word gecontroleerd op:
                - Leeftijd partner 1 (ouder dan 18 op trouwdatum)
                - Leeftijd partner 2 (ouder dan 18 op trouwdatum)
                - Bevestiging partner 1 
                - Bevestiging partner 2 
                - Aantal partners (minimaal 2, maximaal 2)
                - Huwelijksstaat partner 1 (geen huidige partner, WORD PAS GECONTROLEERD NA BEVESTIGING BIJDE PARTNERS)
                - Huwelijksstaat partner 2 (geen huidige partner, WORD PAS GECONTROLEERD NA BEVESTIGING BIJDE PARTNERS)
                - Bloedverwantschap (geen fammilie in de tweede graad)
              properties:
                result:
                  type: boolean
                display:
                  type: string
            getuigen:
              type: object
              description: |-
                Onder getuigen word gecontrolleerd of:
                - Heeft iedere partner minimaal 1 getuigen
                - Heeft iedere partner maximaal 2 getuigen
                - Hebben alle getuigen ingestemd
              properties:
                result:
                  type: boolean
                display:
                  type: string
            ambtenaar:
              type: object
              description: |-
                Onder ambtenaar wordt er gecontroleerd op:
                - Is er een trouwambtenaar aan het huwelijk gekoppeld
                - Is deze gereserveerd en beschickbaar
                - Heeft deze bevestigd
              properties:
                result:
                  type: boolean
                display:
                  type: string
            moment:
              type: object
              description: |-
                Onder moment wordt er gecontroleerd op:
                - Is het moment minimaal 2 weken in de toekomst
                - Is het moment maximaal 1 jaar in de toekomst
                - Vanaf de status "melding" worden deze controles niet meer geupdate
              properties:
                result:
                  type: boolean
                display:
                  type: string
            producten:
              type: object
              description: |-
                Onder producten word gecontroleerd op:
                - Niks, producten zijn optioneel
              properties:
                result:
                  type: boolean
                display:
                  type: string
            order:
              type: object
              description: |-
                Onder order wordt er gecontroleerd op:
                - Is er een order
                - Is het totaal van de order gelijk aan het totaal van het huwelijks
                - Is de order betaald
              properties:
                result:
                  type: boolean
                display:
                  type: string
            zaak:
              type: object
              description: |-
                Onder zaak wordt gecontroleerd op:
                - afhankenlijk van gemeentenlijke configuratie
              properties:
                result:
                  type: boolean
                display:
                  type: string
                  example: Uw heeft uw huwelijk betaald
          readOnly: true
        order:
          type: string
          description: "Bij het melden van het voorgenomen huwelijk word een order gecreërd. Dit order bevat ook de betaallink. , bij ophalen kan de query parameter &extend[]=order worden gebruikt om een volledig object op te halen."
          format: url
          example: "https://www.zuiddrecht.nl/api/orc/vi/ea16b2d6-3e0f-43d7-abf2-069569b2ee54"
          readOnly: true
        zaak:
          x-context: schema.conduction.nl/zaak
          type: string
          description: "Een zaak bevat de ZRC verwijzing naar een zaak, mits de gemeente deze als verplicht heet ingecalculeerd. De zaak wordt onderwater autotmatisch gecreerd. , bij ophalen kan de query parameter &extend[]=zaak worden gebruikt om een volledig object op te halen."
          example: "https://www.zuiddrecht.nl/api/zrc/vi/ea16b2d6-3e0f-43d7-abf2-069569b2ee54"
          readOnly: true
        kosten:
          type: string
          description: "Een ISO kosten opgaaf voor het huwelijk bestaande uit een drie cijferige valuta code gevold door het bedrag zonder decimalen e.g. EUR 150 voor € 1,50"
          example: EUR 150
          readOnly: true
        instemmingGemeente:
          x-context: schema.conduction.nl/assent
          description: De verwijzing van de isntemming van de gemeente met het huwelijk of parterschap
